
MODEL_TEMPLATE_AND_PATH = {
    "llava": {
        "path": "liuhaotian/llava-v1.6-vicuna-7b",
        "template": "llava-chatml",
        "patch_size": 24,
        "image_size": 24*24
    },
    "blip2": {
        "path": "Salesforce/blip2-opt-2.7b",
        "template": "blip",
        "patch_size": 32,
        "image_size": 224
    },
    "instruct-blip": {
        "path": "Salesforce/instructblip-vicuna-7b",
        "template": "instruct-blip",
        "patch_size": 32,
        "image_size": 224
    }
}


CLS_INSTRUCTIONS = [
    "Imagine you're explaining this image to someone over the phone. Please describe the image in one word?",
    "Perform the image classification task on this image. Give the label in one word.",
    "Imagine a child is trying to identify the image. What might they excitedly point to and name?",
    "If this image were turned into a jigsaw puzzle, what would the box label say to describe the picture inside?",
    "Classify the content of this image.",
    "If you were to label this image, what label would you give?",
    "What category best describes this image?",
    "Describe the central subject of this image in a single word.",
    "Provide a classification for the object depicted in this image.",
    "If this image were in a photo album, what would its label be?",
    "Categorize the content of the image.",
    "If you were to sort this image into a category, which one would it be?",
    "What keyword would you associate with this image?",
    "Assign a relevant classification to this image.",
    "If this image were in a gallery, under which section would it belong?",
    "Describe the main theme of this image in one word.",
    "Under which category would this image be cataloged in a library?",
    "What classification tag fits this image the best?",
    "Provide a one-word description of this image's content.",
    "If you were to archive this image, what descriptor would you use?",
    "Identify the primary theme of this image in one word.",
    "How would you label this image with a single descriptor?",
    "Determine the main category for this image.",
    "Offer a one-word identifier for this picture.",
    "If this image were a file on your computer, what would its name be?",
    "Tag this image with its most relevant keyword.",
    "Provide the primary classification for this photograph.",
    "How would you succinctly categorize this image?",
    "Offer the primary descriptor for the content of this image.",
    "If this image were a product, what label would you place on its box?",
    "Choose a single word that encapsulates the image's content.",
    "How would you classify this image in a database?",
    "In one word, describe the essence of this image.",
    "Provide the most fitting category for this image.",
    "What is the principal subject of this image?",
    "If this image were in a store, which aisle would it belong to?",
    "Provide a singular term that characterizes this picture.",
    "How would you caption this image in a photo contest?",
    "Select a label that fits the main theme of this image.",
    "Offer the most appropriate tag for this image.",
    "Which keyword best summarizes this image?",
    "How would you title this image in an exhibition?",
    "Provide a succinct identifier for the image's content.",
    "Choose a word that best groups this image with others like it.",
    "If this image were in a museum, how would it be labeled?",
    "Assign a central theme to this image in one word.",
    "Tag this photograph with its primary descriptor.",
    "What is the overriding theme of this picture?",
    "Provide a classification term for this image.",
    "How would you sort this image in a collection?",
    "Identify the main subject of this image concisely.",
    "If this image were a magazine cover, what would its title be?",
    "What term would you use to catalog this image?",
    "Classify this picture with a singular term.",
    "If this image were a chapter in a book, what would its title be?",
    "Select the most fitting classification for this image.",
    "Define the essence of this image in one word.",
    "How would you label this image for easy retrieval?",
    "Determine the core theme of this photograph.",
    "In a word, encapsulate the main subject of this image.",
    "If this image were an art piece, how would it be labeled in a gallery?",
    "Provide the most concise descriptor for this picture.",
    "How would you name this image in a photo archive?",
    "Choose a word that defines the image's main content.",
    "What would be the header for this image in a catalog?",
    "Classify the primary essence of this picture.",
    "What label would best fit this image in a slideshow?",
    "Determine the dominant category for this photograph.",
    "Offer the core descriptor for this image.",
    "If this image were in a textbook, how would it be labeled in the index?",
    "Select the keyword that best defines this image's theme.",
    "Provide a classification label for this image.",
    "If this image were a song title, what would it be?",
    "Identify the main genre of this picture.",
    "Assign the most apt category to this image.",
    "Describe the overarching theme of this image in one word.",
    "What descriptor would you use for this image in a portfolio?",
    "Summarize the image's content with a single identifier."
]


CAP_INSTRUCTIONS = [
    "Describe the content of this image.",
    "What's happening in this image?",
    "Provide a brief caption for this image.",
    "Tell a story about this image in one sentence.",
    "If this image could speak, what would it say?",
    "Summarize the scenario depicted in this image.",
    "What is the central theme or event shown in the picture?",
    "Create a headline for this image.",
    "Explain the scene captured in this image.",
    "If this were a postcard, what message would it convey?",
    "Narrate the visual elements present in this image.",
    "Give a short title to this image.",
    "How would you describe this image to someone who can't see it?",
    "Detail the primary action or subject in the photo.",
    "If this image were the cover of a book, what would its title be?",
    "Translate the emotion or event of this image into words.",
    "Compose a one-liner describing this image's content.",
    "Imagine this image in a magazine. What caption would go with it?",
    "Capture the essence of this image in a brief description.",
    "Narrate the visual story displayed in this photograph.",
    "Elaborate on the elements present in this image.",
    "In one sentence, summarize the activity in this image.",
    "Relate the main components of this picture in words.",
    "What narrative unfolds in this image?",
    "Break down the main subjects of this photo.",
    "Give an account of the main scene in this image.",
    "In a few words, state what this image represents.",
    "Describe the setting or location captured in this photograph.",
    "Provide an overview of the subjects or objects seen in this picture.",
    "Identify the primary focus or point of interest in this image.",
    "What would be the perfect title for this image?",
    "How would you introduce this image in a presentation?",
    "Present a quick rundown of the image's main subject.",
    "What's the key event or subject captured in this photograph?",
    "Relate the actions or events taking place in this image.",
    "Convey the content of this photograph in a single phrase.",
    "Offer a succinct description of this picture.",
    "Give a concise overview of this image.",
    "Translate the contents of this picture into a sentence.",
    "Describe the characters or subjects seen in this image.",
    "Capture the activities happening in this image with words.",
    "How would you introduce this image to an audience?",
    "State the primary events or subjects in this picture.",
    "What are the main elements in this photograph?",
    "Provide an interpretation of this image's main event or subject.",
    "How would you title this image for an art gallery?",
    "What scenario or setting is depicted in this image?",
    "Concisely state the main actions occurring in this image.",
    "Offer a short summary of this photograph's contents.",
    "How would you annotate this image in an album?",
    "If you were to describe this image on the radio, how would you do it?",
    "In your own words, narrate the main event in this image.",
    "What are the notable features of this image?",
    "Break down the story this image is trying to tell.",
    "Describe the environment or backdrop in this photograph.",
    "How would you label this image in a catalog?",
    "Convey the main theme of this picture succinctly.",
    "Characterize the primary event or action in this image.",
    "Provide a concise depiction of this photo's content.",
    "Write a brief overview of what's taking place in this image.",
    "Illustrate the main theme of this image with words.",
    "How would you describe this image in a gallery exhibit?",
    "Highlight the central subjects or actions in this image.",
    "Offer a brief narrative of the events in this photograph.",
    "Translate the activities in this image into a brief sentence.",
    "Give a quick rundown of the primary subjects in this image.",
    "Provide a quick summary of the scene captured in this photo.",
    "How would you explain this image to a child?",
    "What are the dominant subjects or objects in this photograph?",
    "Summarize the main events or actions in this image.",
    "Describe the context or setting of this image briefly.",
    "Offer a short description of the subjects present in this image.",
    "Detail the main scenario or setting seen in this picture.",
    "Describe the main activities or events unfolding in this image.",
    "Provide a concise explanation of the content in this image.",
    "If this image were in a textbook, how would it be captioned?",
    "Provide a summary of the primary focus of this image.",
    "State the narrative or story portrayed in this picture.",
    "How would you introduce this image in a documentary?",
    "Detail the subjects or events captured in this image.",
    "Offer a brief account of the scenario depicted in this photograph.",
    "State the main elements present in this image concisely.",
    "Describe the actions or events happening in this picture.",
    "Provide a snapshot description of this image's content.",
    "How would you briefly describe this image's main subject or event?"
]

VQA_INSTRUCTIONS = [
    'Any cutlery items visible in the image? If not, please tell what is in the image?',
    'Any bicycles visible in this image? If not, please tell what is in the image?',
    'Any boats visible in the image? If not, please tell what is in the image?',
    'Any bottles present in the image? If not, please tell what is in the image?',
    'Are curtains noticeable in the image? If not, please tell what is in the image?',
    'Are flags present in the image? If not, please tell what is in the image?',
    'Are flowers present in the image? If not, please tell what is in the image?',
    'Are fruits present in the image? If not, please tell what is in the image?',
    'Are glasses discernible in the image? If not, please tell what is in the image?',
    'Are hills visible in the image? If not, please tell what is in the image?',
    'Are plates discernible in the image? If not, please tell what is in the image?',
    'Are shoes visible in this image? If not, please tell what is in the image?',
    'Are there any insects in the image? If not, please tell what is in the image?',
    'Are there any ladders in the image? If not, please tell what is in the image?',
    'Are there any man-made structures in the image? If not, please tell what is in the image?',
    'Are there any signs or markings in the image? If not, please tell what is in the image?',
    'Are there any street signs in the image? If not, please tell what is in the image?',
    'Are there balloons in the image? If not, please tell what is in the image?',
    'Are there bridges in the image? If not, please tell what is in the image?',
    'Are there musical notes in the image? If not, please tell what is in the image?',
    'Are there people sitting in the image? If not, please tell what is in the image?',
    'Are there skyscrapers in the image? If not, please tell what is in the image?',
    'Are there toys in the image? If not, please tell what is in the image?',
    'Are toys present in this image? If not, please tell what is in the image?',
    'Are umbrellas discernible in the image? If not, please tell what is in the image?',
    'Are windows visible in the image? If not, please tell what is in the image?',
    'Can birds be seen in this image? If not, please tell what is in the image?',
    'Can stars be seen in this image? If not, please tell what is in the image?',
    'Can we find any bags in this image? If not, please tell what is in the image?',
    'Can you find a crowd in the image? If not, please tell what is in the image?',
    'Can you find a hat in the image? If not, please tell what is in the image?',
    'Can you find any musical instruments in this image? If not, please tell what is in the image?',
    'Can you identify a clock in this image? If not, please tell what is in the image?',
    'Can you identify a computer in this image? If not, please tell what is in the image?',
    'Can you see a beach in the image? If not, please tell what is in the image?',
    'Can you see a bus in the image? If not, please tell what is in the image?',
    'Can you see a mailbox in the image? If not, please tell what is in the image?',
    'Can you see a mountain in the image? If not, please tell what is in the image?',
    'Can you see a staircase in the image? If not, please tell what is in the image?',
    'Can you see a stove or oven in the image? If not, please tell what is in the image?',
    'Can you see a sunset in the image? If not, please tell what is in the image?',
    'Can you see any cups or mugs in the image? If not, please tell what is in the image?',
    'Can you see any jewelry in the image? If not, please tell what is in the image?',
    'Can you see shadows in the image? If not, please tell what is in the image?',
    'Can you see the sky in the image? If not, please tell what is in the image?',
    'Can you spot a candle in this image? If not, please tell what is in the image?',
    'Can you spot a farm in this image? If not, please tell what is in the image?',
    'Can you spot a pair of shoes in the image? If not, please tell what is in the image?',
    'Can you spot a rug or carpet in the image? If not, please tell what is in the image?',
    'Can you spot any dogs in the image? If not, please tell what is in the image?',
    'Can you spot any snow in the image? If not, please tell what is in the image?',
    'Do you notice a bicycle in the image? If not, please tell what is in the image?',
    'Does a ball feature in this image? If not, please tell what is in the image?',
    'Does a bridge appear in the image? If not, please tell what is in the image?',
    'Does a cat appear in the image? If not, please tell what is in the image?',
    'Does a fence appear in the image? If not, please tell what is in the image?',
    'Does a fire feature in this image? If not, please tell what is in the image?',
    'Does a mirror feature in this image? If not, please tell what is in the image?',
    'Does a table feature in this image? If not, please tell what is in the image?',
    'Does it appear to be nighttime in the image? If not, please tell what is in the image?',
    'Does it look like an outdoor image? If not, please tell what is in the image?',
    'Does it seem to be countryside in the image? If not, please tell what is in the image?',
    'Does the image appear to be a cartoon or comic strip? If not, please tell what is in the image?',
    'Does the image contain any books? If not, please tell what is in the image?',
    'Does the image contain any electronic devices? If not, please tell what is in the image?',
    'Does the image depict a road? If not, please tell what is in the image?',
    'Does the image display a river? If not, please tell what is in the image?',
    'Does the image display any towers? If not, please tell what is in the image?',
    'Does the image feature any art pieces? If not, please tell what is in the image?',
    'Does the image have a lamp? If not, please tell what is in the image?',
    'Does the image have any pillows? If not, please tell what is in the image?',
    'Does the image have any vehicles? If not, please tell what is in the image?',
    'Does the image have furniture? If not, please tell what is in the image?',
    'Does the image primarily display natural elements? If not, please tell what is in the image?',
    'Does the image seem like it was taken during the day? If not, please tell what is in the image?',
    'Does the image seem to be taken indoors? If not, please tell what is in the image?',
    'Does the image show any airplanes? If not, please tell what is in the image?',
    'Does the image show any benches? If not, please tell what is in the image?',
    'Does the image show any landscapes? If not, please tell what is in the image?',
    'Does the image show any movement? If not, please tell what is in the image?',
    'Does the image show any sculptures? If not, please tell what is in the image?',
    'Does the image show any signs? If not, please tell what is in the image?',
    'Does the image show food? If not, please tell what is in the image?',
    'Does the image showcase a building? If not, please tell what is in the image?',
    'How many animals are present in the image? And tell me what is in the image?',
    'How many bikes are present in the image? And tell me what is in the image?',
    'How many birds are visible in the image? And tell me what is in the image?',
    'How many buildings can be identified in the image? And tell me what is in the image?',
    'How many cars can be seen in the image? And tell me what is in the image?',
    'How many doors can you spot in the image? And tell me what is in the image?',
    'How many flowers can be identified in the image? And tell me what is in the image?',
    'How many trees feature in the image? And tell me what is in the image?',
    'Is a chair noticeable in the image? If not, please tell what is in the image?',
    'Is a computer visible in the image? If not, please tell what is in the image?',
    'Is a forest noticeable in the image? If not, please tell what is in the image?',
    'Is a painting visible in the image? If not, please tell what is in the image?',
    'Is a path or trail visible in the image? If not, please tell what is in the image?',
    'Is a phone discernible in the image? If not, please tell what is in the image?',
    'Is a train noticeable in the image? If not, please tell what is in the image?',
    'Is sand visible in the image? If not, please tell what is in the image?',
    'Is the image displaying any clouds? If not, please tell what is in the image?',
    'Is the image set in a city environment? If not, please tell what is in the image?',
    'Is there a plant in the image? If not, please tell what is in the image?',
    'Is there a source of light visible in the image? If not, please tell what is in the image?',
    'Is there a television displayed in the image? If not, please tell what is in the image?',
    'Is there grass in the image? If not, please tell what is in the image?',
    'Is there text in the image? If not, please tell what is in the image?',
    'Is water visible in the image, like a sea, lake, or river? If not, please tell what is in the image?',
    "How many people are captured in the image? And tell me what is in the image?",
    "How many windows can you count in the image? And tell me what is in the image?",
    "How many animals, other than birds, are present? And tell me what is in the image?",
    "How many statues or monuments stand prominently in the scene? And tell me what is in the image?",
    "How many streetlights are visible? And tell me what is in the image?",
    "How many items of clothing can you identify? And tell me what is in the image?",
    "How many shoes can be seen in the image? And tell me what is in the image?",
    "How many clouds appear in the sky? And tell me what is in the image?",
    "How many pathways or trails are evident? And tell me what is in the image?",
    "How many bridges can you spot? And tell me what is in the image?",
    "How many boats are present, if it's a waterscape? And tell me what is in the image?",
    "How many pieces of fruit can you identify? And tell me what is in the image?",
    "How many hats are being worn by people? And tell me what is in the image?",
    "How many different textures can you discern? And tell me what is in the image?",
    "How many signs or billboards are visible? And tell me what is in the image?",
    "How many musical instruments can be seen? And tell me what is in the image?",
    "How many flags are present in the image? And tell me what is in the image?",
    "How many mountains or hills can you identify? And tell me what is in the image?",
    "How many books are visible, if any? And tell me what is in the image?",
    "How many bodies of water, like ponds or pools, are in the scene? And tell me what is in the image?",
    "How many shadows can you spot? And tell me what is in the image?",
    "How many handheld devices, like phones, are present? And tell me what is in the image?",
    "How many pieces of jewelry can be identified? And tell me what is in the image?",
    "How many reflections, perhaps in mirrors or water, are evident? And tell me what is in the image?",
    "How many pieces of artwork or sculptures can you see? And tell me what is in the image?",
    "How many staircases or steps are in the image? And tell me what is in the image?",
    "How many archways or tunnels can be counted? And tell me what is in the image?",
    "How many tools or equipment are visible? And tell me what is in the image?",
    "How many modes of transportation, other than cars and bikes, can you spot? And tell me what is in the image?",
    "How many lamp posts or light sources are there? And tell me what is in the image?",
    "How many plants, other than trees and flowers, feature in the scene? And tell me what is in the image?",
    "How many fences or barriers can be seen? And tell me what is in the image?",
    "How many chairs or seating arrangements can you identify? And tell me what is in the image?",
    "How many different patterns or motifs are evident in clothing or objects? And tell me what is in the image?",
    "How many dishes or food items are visible on a table setting? And tell me what is in the image?",
    "How many glasses or mugs can you spot? And tell me what is in the image?",
    "How many pets or domestic animals are in the scene? And tell me what is in the image?",
    "How many electronic gadgets can be counted? And tell me what is in the image?",
    "Where is the brightest point in the image? And tell me what is in the image?",
    "Where are the darkest areas located? And tell me what is in the image?",
    "Where can one find leading lines directing the viewer's eyes? And tell me what is in the image?",
    "Where is the visual center of gravity in the image? And tell me what is in the image?",
    "Where are the primary and secondary subjects positioned? And tell me what is in the image?",
    "Where do the most vibrant colors appear? And tell me what is in the image?",
    "Where is the most contrasting part of the image located? And tell me what is in the image?",
    "Where does the image place emphasis through scale or size? And tell me what is in the image?",
    "Where do the textures in the image change or transition? And tell me what is in the image?",
    "Where does the image break traditional compositional rules? And tell me what is in the image?",
    "Where do you see repetition or patterns emerging? And tell me what is in the image?",
    "Where does the image exhibit depth or layers? And tell me what is in the image?",
    "Where are the boundary lines or borders in the image? And tell me what is in the image?",
    "Where do different elements in the image intersect or overlap? And tell me what is in the image?",
    "Where does the image hint at motion or movement? And tell me what is in the image?",
    "Where are the calm or restful areas of the image? And tell me what is in the image?",
    "Where does the image become abstract or less defined? And tell me what is in the image?",
    "Where do you see reflections, be it in water, glass, or other surfaces? And tell me what is in the image?",
    "Where does the image provide contextual clues about its setting? And tell me what is in the image?",
    "Where are the most detailed parts of the image? And tell me what is in the image?",
    "Where do you see shadows, and how do they impact the composition? And tell me what is in the image?",
    "Where can you identify different geometric shapes? And tell me what is in the image?",
    "Where does the image appear to have been cropped or framed intentionally? And tell me what is in the image?",
    "Where do you see harmony or unity among the elements? And tell me what is in the image?",
    "Where are there disruptions or interruptions in patterns? And tell me what is in the image?",
    "What is the spacing between objects or subjects in the image?",
    "What foreground, mid-ground, and background elements can be differentiated?",
    "What type of energy or vibe does the image exude?",
    "What might be the sound environment based on the image's content?",
    "What abstract ideas or concepts does the image seem to touch upon?",
    "What is the relationship between the main subjects in the image?",
    "What items in the image could be considered rare or unique?",
    "What is the gradient or transition of colors like in the image?",
    "What might be the smell or aroma based on the image's content?",
    "What type of textures can be felt if one could touch the image's content?",
    "What boundaries or limits are depicted in the image?",
    "What is the socioeconomic context implied by the image?",
    "What might be the immediate aftermath of the scene in the image?",
    "What seems to be the main source of tension or harmony in the image?",
    "What might be the narrative or backstory of the main subject?",
    "What elements of the image give it its primary visual weight?",
    'Would you describe the image as bright or dark?',
    'Would you describe the image as colorful or dull?',
]
